import { Brand, CheckSession, BarcodeCheckResult, CheckItem } from '@/types';

export const MOCK_BRANDS: Brand[] = [
    {
        id: 'innisfree',
        name: 'Innisfree',
        logoUrl: '/logos/innisfree.png',
        companyName: 'AmorePacific Vietnam Co., Ltd.',
        address: 'Tầng 10, Tòa nhà Vietcombank, 5 Công Trường Mê Linh, Quận 1, TP.HCM',
        phone: '1800 1234',
        website: 'www.innisfree.com.vn',
        color: '#2D6A4F',
    },
    {
        id: 'loreal',
        name: "L'Oréal",
        logoUrl: '/logos/loreal.png',
        companyName: "L'Oréal Vietnam Co., Ltd.",
        address: '12 Tôn Đản, Phường 13, Quận 4, TP.HCM',
        phone: '1800 5678',
        website: 'www.loreal.com.vn',
        color: '#C8102E',
    },
    {
        id: 'cocoon',
        name: 'Cocoon',
        logoUrl: '/logos/cocoon.png',
        companyName: 'Công ty TNHH Nature Story',
        address: '123 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
        phone: '028 3939 1234',
        website: 'www.cocoonoriginal.com',
        color: '#8B5E3C',
    },
    {
        id: 'thefaceshop',
        name: 'The Face Shop',
        logoUrl: '/logos/thefaceshop.png',
        companyName: 'LG H&H Vietnam Co., Ltd.',
        address: '72 Lê Thánh Tôn, Bến Nghé, Quận 1, TP.HCM',
        phone: '1800 9090',
        website: 'www.thefaceshop.com.vn',
        color: '#4A7C59',
    },
];

const barcodeResult1: BarcodeCheckResult = {
    scanability: 94,
    colorStatus: 'ok',
    colorNote: 'Vạch đen trên nền trắng — Đạt chuẩn',
    detectedColor: '#1A1A1A on #FFFFFF',
    expectedColor: 'Đen trên trắng',
    width: 3.2,
    height: 1.8,
    widthStatus: 'ok',
    heightStatus: 'ok',
    quietZoneStatus: 'ok',
    quietZoneNote: 'Vùng trống đủ rộng (>2mm mỗi bên)',
    comparisonStatus: 'ok',
    comparisonNote: 'Khớp 100% với file mã vạch gốc',
};

const barcodeResult2: BarcodeCheckResult = {
    scanability: 61,
    colorStatus: 'error',
    colorNote: 'Phát hiện nền tối + vạch sáng (đảo màu) — Không đạt',
    detectedColor: '#FFFFFF on #2C2C2C',
    expectedColor: 'Đen trên trắng',
    width: 2.1,
    height: 1.1,
    widthStatus: 'warning',
    heightStatus: 'error',
    quietZoneStatus: 'warning',
    quietZoneNote: 'Quiet zone bên phải chỉ 1mm — Cần tối thiểu 2mm',
    comparisonStatus: 'ok',
    comparisonNote: 'Khớp 100% với file mã vạch gốc',
};

const contentItems1: CheckItem[] = [
    {
        id: 'logo',
        field: 'Logo thương hiệu',
        expected: 'Logo Innisfree chuẩn (v3.2)',
        found: 'Logo Innisfree (phát hiện trên nhãn)',
        status: 'ok',
        note: '',
        region: { x: 5, y: 5, w: 20, h: 12 },
    },
    {
        id: 'company',
        field: 'Tổ chức chịu trách nhiệm',
        expected: 'AmorePacific Vietnam Co., Ltd. — Tầng 10, Tòa nhà Vietcombank...',
        found: 'AmorePacific Vietnam Co., Ltd. — Tầng 10, Tòa nhà Vietcombank...',
        status: 'ok',
        note: '',
        region: { x: 5, y: 75, w: 60, h: 8 },
    },
    {
        id: 'product_name',
        field: 'Tên sản phẩm (chính)',
        expected: 'Green Tea Seed Serum',
        found: 'Green Tea Seed Serum',
        status: 'ok',
        note: '',
        region: { x: 10, y: 20, w: 80, h: 10 },
    },
    {
        id: 'product_name_vi',
        field: 'Tên sản phẩm (phụ/dịch)',
        expected: 'Tinh chất dưỡng ẩm hạt trà xanh',
        found: 'Tinh chất dưỡng ẩm hạt trà xanh',
        status: 'ok',
        note: '',
        region: { x: 10, y: 30, w: 80, h: 6 },
    },
    {
        id: 'volume',
        field: 'Định lượng',
        expected: '80 ml ℮ 2.7 fl.oz',
        found: '80ml ℮ 2.7 fl.oz',
        status: 'error',
        note: 'Thiếu khoảng cách giữa số và đơn vị: "80ml" → phải là "80 ml"',
        region: { x: 70, y: 85, w: 25, h: 6 },
    },
    {
        id: 'ingredients',
        field: 'Thành phần (Ingredients)',
        expected: '45 thành phần theo HSCB mục 11',
        found: '45 thành phần — Khớp thứ tự và nội dung',
        status: 'ok',
        note: '',
        region: { x: 5, y: 55, w: 90, h: 18 },
    },
    {
        id: 'usage',
        field: 'Công dụng',
        expected: 'Dưỡng ẩm, cấp nước chuyên sâu cho da',
        found: 'Dưỡng ẩm, cấp nước chuyên sâu cho da',
        status: 'ok',
        note: '',
        region: { x: 5, y: 45, w: 90, h: 8 },
    },
    {
        id: 'notification_no',
        field: 'Số công bố',
        expected: '210000123/CBMP-HN',
        found: '210000123/CBMP-HN',
        status: 'ok',
        note: '',
        region: { x: 5, y: 85, w: 40, h: 5 },
    },
    {
        id: 'origin',
        field: 'Xuất xứ',
        expected: 'Một trong 5 cụm từ bắt buộc',
        found: '"Made in Korea" — Đạt',
        status: 'ok',
        note: '',
        region: { x: 5, y: 90, w: 40, h: 5 },
    },
    {
        id: 'pao',
        field: 'Hạn sử dụng (PAO)',
        expected: 'Biểu tượng hộp mở nắp (6M/12M/24M)',
        found: '12M — Phát hiện biểu tượng PAO',
        status: 'ok',
        note: '',
        region: { x: 80, y: 5, w: 15, h: 10 },
    },
    {
        id: 'forbidden_words',
        field: 'Từ ngữ cấm',
        expected: 'Không có từ ngữ điều trị/y khoa',
        found: 'Không phát hiện từ ngữ cấm',
        status: 'ok',
        note: '',
    },
];

const contentItems2: CheckItem[] = [
    {
        id: 'logo',
        field: 'Logo thương hiệu',
        expected: "Logo L'Oréal chuẩn (v2.1)",
        found: 'Logo phát hiện — Cần xác nhận thủ công',
        status: 'warning',
        note: 'Không thể so sánh tự động — Vui lòng kiểm tra thủ công',
        region: { x: 5, y: 5, w: 25, h: 15 },
    },
    {
        id: 'company',
        field: 'Tổ chức chịu trách nhiệm',
        expected: "L'Oréal Vietnam Co., Ltd. — 12 Tôn Đản...",
        found: "L'Oreal Vietnam Co., Ltd. — 12 Tôn Đản...",
        status: 'error',
        note: 'Sai chính tả: "L\'Oreal" thiếu dấu accent → phải là "L\'Oréal"',
        region: { x: 5, y: 75, w: 65, h: 8 },
    },
    {
        id: 'product_name',
        field: 'Tên sản phẩm (chính)',
        expected: 'Revitalift Laser X3 Anti-Aging Serum',
        found: 'Revitalift Laser X3 Anti-Aging Serum',
        status: 'ok',
        note: '',
        region: { x: 10, y: 20, w: 80, h: 10 },
    },
    {
        id: 'usp_claim',
        field: 'USP Claim — "X3"',
        expected: 'Cần hồ sơ chứng minh cho claim "X3"',
        found: '"X3" phát hiện trên nhãn',
        status: 'warning',
        note: 'Cảnh báo USP: Claim "X3" yêu cầu hồ sơ chứng minh. Xác nhận đã có tài liệu?',
        region: { x: 10, y: 20, w: 80, h: 10 },
    },
    {
        id: 'volume',
        field: 'Định lượng',
        expected: '30 ml ℮ 1.0 fl.oz',
        found: '30 ml ℮ 1.0 fl.oz',
        status: 'ok',
        note: '',
        region: { x: 70, y: 85, w: 25, h: 6 },
    },
    {
        id: 'ingredients',
        field: 'Thành phần (Ingredients)',
        expected: '38 thành phần theo HSCB mục 11',
        found: '36 thành phần — Thiếu 2 thành phần',
        status: 'error',
        note: 'Thiếu: "Adenosine" và "Niacinamide" so với HSCB mục 11',
        region: { x: 5, y: 55, w: 90, h: 18 },
    },
    {
        id: 'usage',
        field: 'Công dụng',
        expected: 'Giảm nếp nhăn, làm sáng da',
        found: 'Trị nếp nhăn, làm sáng da',
        status: 'error',
        note: 'Từ ngữ cấm: "Trị" → gợi ý sửa thành "Giảm" hoặc "Cải thiện"',
        region: { x: 5, y: 45, w: 90, h: 8 },
    },
    {
        id: 'notification_no',
        field: 'Số công bố',
        expected: '220000456/CBMP-HCM',
        found: '220000456/CBMP-HCM',
        status: 'ok',
        note: '',
        region: { x: 5, y: 85, w: 40, h: 5 },
    },
    {
        id: 'origin',
        field: 'Xuất xứ',
        expected: 'Một trong 5 cụm từ bắt buộc',
        found: 'Không tìm thấy cụm từ xuất xứ bắt buộc',
        status: 'error',
        note: 'Thiếu xuất xứ. Cần thêm: "Made in France" hoặc "Sản xuất tại Pháp"',
        region: { x: 5, y: 90, w: 40, h: 5 },
    },
    {
        id: 'pao',
        field: 'Hạn sử dụng (PAO)',
        expected: 'Biểu tượng hộp mở nắp (6M/12M/24M)',
        found: 'Không phát hiện biểu tượng PAO',
        status: 'error',
        note: 'Thiếu biểu tượng PAO (hộp mở nắp). Cần bổ sung 12M hoặc 24M',
        region: { x: 80, y: 5, w: 15, h: 10 },
    },
    {
        id: 'forbidden_words',
        field: 'Từ ngữ cấm',
        expected: 'Không có từ ngữ điều trị/y khoa',
        found: 'Phát hiện từ "Trị" trong phần công dụng',
        status: 'error',
        note: '"Trị nếp nhăn" → Gợi ý: "Giảm nếp nhăn" hoặc "Cải thiện nếp nhăn"',
    },
];

const contentItems3: CheckItem[] = [
    {
        id: 'product_name',
        field: 'Tên sản phẩm (chính)',
        expected: 'Cà Phê Đắk Lắk Lip Balm',
        found: 'Cà Phê Đắk Lắk Lip Balm',
        status: 'ok',
        note: '',
        region: { x: 10, y: 20, w: 80, h: 10 },
    },
    {
        id: 'lot_number',
        field: 'Số lô',
        expected: 'Có số lô trên bao bì',
        found: 'LOT: 2024-08-A',
        status: 'ok',
        note: '',
        region: { x: 5, y: 85, w: 40, h: 5 },
    },
    {
        id: 'company',
        field: 'Tổ chức chịu trách nhiệm',
        expected: 'Thông tin trên nhãn phụ/bao bì ngoài',
        found: 'Không có trên nhãn chính (sản phẩm <20ml)',
        status: 'warning',
        note: 'Sản phẩm <20ml: Thông tin này cần có trên nhãn phụ hoặc bao bì ngoài',
    },
    {
        id: 'ingredients',
        field: 'Thành phần (Ingredients)',
        expected: 'Thông tin trên nhãn phụ/bao bì ngoài',
        found: 'Không có trên nhãn chính (sản phẩm <20ml)',
        status: 'warning',
        note: 'Sản phẩm <20ml: Thành phần cần có trên nhãn phụ hoặc bao bì ngoài',
    },
    {
        id: 'volume',
        field: 'Định lượng',
        expected: '10 g ℮ 0.4 oz',
        found: '10 g ℮ 0.4 oz',
        status: 'ok',
        note: '',
        region: { x: 70, y: 85, w: 25, h: 6 },
    },
];

export const MOCK_SESSIONS: CheckSession[] = [
    {
        id: 'chk-001',
        productName: 'Green Tea Seed Serum',
        brandId: 'innisfree',
        brandName: 'Innisfree',
        labelType: '>20ml',
        volume: '80 ml',
        volumeFormatted: '80 ml ℮ 2.7 fl.oz',
        status: 'fail',
        createdAt: '2026-02-18T08:30:00+07:00',
        checkedBy: 'Nguyen Thi A',
        barcodeResult: barcodeResult1,
        contentItems: contentItems1,
        totalErrors: 1,
        totalWarnings: 0,
        totalOk: 10,
    },
    {
        id: 'chk-002',
        productName: 'Revitalift Laser X3 Anti-Aging Serum',
        brandId: 'loreal',
        brandName: "L'Oréal",
        labelType: '>20ml',
        volume: '30 ml',
        volumeFormatted: '30 ml ℮ 1.0 fl.oz',
        status: 'fail',
        createdAt: '2026-02-17T14:15:00+07:00',
        checkedBy: 'Tran Van B',
        barcodeResult: barcodeResult2,
        contentItems: contentItems2,
        totalErrors: 6,
        totalWarnings: 2,
        totalOk: 3,
    },
    {
        id: 'chk-003',
        productName: 'Cà Phê Đắk Lắk Lip Balm',
        brandId: 'cocoon',
        brandName: 'Cocoon',
        labelType: '<20ml',
        volume: '10 g',
        volumeFormatted: '10 g ℮ 0.4 oz',
        status: 'pass',
        createdAt: '2026-02-16T09:00:00+07:00',
        checkedBy: 'Le Thi C',
        barcodeResult: {
            scanability: 88,
            colorStatus: 'ok',
            colorNote: 'Vạch đen trên nền trắng — Đạt chuẩn',
            detectedColor: '#1A1A1A on #FFFFFF',
            expectedColor: 'Đen trên trắng',
            width: 2.8,
            height: 1.5,
            widthStatus: 'ok',
            heightStatus: 'ok',
            quietZoneStatus: 'ok',
            quietZoneNote: 'Vùng trống đủ rộng',
            comparisonStatus: 'ok',
            comparisonNote: 'Khớp 100% với file mã vạch gốc',
        },
        contentItems: contentItems3,
        totalErrors: 0,
        totalWarnings: 2,
        totalOk: 3,
    },
];
